import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import Image from 'next/image';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-white min-h-screen flex flex-col">
        <header className="w-full shadow-sm bg-white sticky top-0 z-50">
          <nav className="container mx-auto flex items-center justify-between py-3 px-4">
            <Link href="/" className="flex items-center gap-2">
              <Image src="/logo-codevendi.png" alt="Codevendi Logo" width={180} height={40} priority />
            </Link>
            <ul className="flex gap-8 text-lg font-medium text-gray-800">
              <li><Link href="/" className="hover:text-yellow-500 transition">Inicio</Link></li>
              <li><Link href="/catalogo" className="hover:text-yellow-500 transition">Catálogo de Softwares</Link></li>
              <li><Link href="/porque-codevendi" className="hover:text-yellow-500 transition">¿Por qué Codevendi?</Link></li>
              <li><Link href="/contacto" className="hover:text-yellow-500 transition">Contacto</Link></li>
              <li><Link href="/carrito" className="hover:text-yellow-500 transition flex items-center gap-1"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6"><path strokeLinecap="round" strokeLinejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.836l.383 1.437m0 0l1.7 6.385m-.383-7.822L6.75 15.75A2.25 2.25 0 008.995 18h6.01a2.25 2.25 0 002.244-2.25l.563-10.125m-13.5 0h15.75" /></svg>Carrito</Link></li>
            </ul>
            <div className="flex gap-4 ml-6">
              <Link href="/login" className="px-4 py-2 rounded-full border border-yellow-500 text-yellow-500 hover:bg-yellow-500 hover:text-white font-semibold transition">Iniciar sesión</Link>
              <Link href="/register" className="px-4 py-2 rounded-full bg-yellow-500 text-white hover:bg-yellow-400 font-semibold transition">Registrarse</Link>
            </div>
          </nav>
        </header>
        <main className="flex-1 container mx-auto px-4 py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
